/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: Robert Joseph George
-/

module

public import Mathlib.LinearAlgebra.AffineSpace.AffineMap

/-!
# KDA context-parallel composition

KDA Context Parallelism summarizes each sequence segment by an affine endomorphism of the
recurrent state. Its linear part propagates the state entering the segment, while its value at zero
is the state generated by that segment. Mathlib's `AffineMap` already provides the correct identity,
composition, associativity, and monoid laws, so this module only defines the segment constructor and
the ordered composition of rank-local summaries.

The K3 state is a real vector space. The statements are kept over an arbitrary ring and module
because no analytic or order structure is needed for the prefix-scan argument.
-/

@[expose] public section

namespace KimiK3.ContextParallel

variable {𝕜 State : Type} [Ring 𝕜] [AddCommGroup State] [Module 𝕜 State]

/-- The affine summary `state ↦ generated + transition state` of one sequence segment. -/
def segment (transition : Module.End 𝕜 State) (generated : State) : State →ᵃ[𝕜] State :=
  transition.toAffineMap + AffineMap.const 𝕜 State generated

@[simp]
theorem segment_apply (transition : Module.End 𝕜 State) (generated state : State) :
    segment transition generated state = generated + transition state := by
  simp [segment, add_comm]

@[simp]
theorem segment_linear (transition : Module.End 𝕜 State) (generated : State) :
    (segment transition generated).linear = transition := by
  simp [segment]

/-- Every affine state summary is recovered from its linear part and zero-state output. -/
theorem segment_linear_apply_zero (summary : State →ᵃ[𝕜] State) :
    segment summary.linear (summary 0) = summary := by
  ext state
  rw [segment_apply]
  simpa [add_comm] using (summary.map_vadd 0 state).symm

/-- Compose rank-local summaries in sequence order. The first list element executes first. -/
def composeAll : List (State →ᵃ[𝕜] State) → State →ᵃ[𝕜] State
  | [] => AffineMap.id 𝕜 State
  | first :: rest => (composeAll rest).comp first

@[simp]
theorem composeAll_nil : composeAll ([] : List (State →ᵃ[𝕜] State)) = AffineMap.id 𝕜 State :=
  rfl

@[simp]
theorem composeAll_cons (first : State →ᵃ[𝕜] State)
    (rest : List (State →ᵃ[𝕜] State)) :
    composeAll (first :: rest) = (composeAll rest).comp first :=
  rfl

/-- Applying the composed summary is exactly sequential left-to-right execution. -/
theorem composeAll_apply (segments : List (State →ᵃ[𝕜] State)) (state : State) :
    composeAll segments state = segments.foldl (fun current next => next current) state := by
  induction segments generalizing state with
  | nil => simp [composeAll]
  | cons first rest ih =>
      rw [composeAll_cons, AffineMap.comp_apply, ih]
      simp only [List.foldl_cons]

/-- Appending segment summaries composes the later summary after the earlier one. -/
theorem composeAll_append (earlier later : List (State →ᵃ[𝕜] State)) :
    composeAll (earlier ++ later) = (composeAll later).comp (composeAll earlier) := by
  ext state
  simp only [composeAll_apply, AffineMap.comp_apply, List.foldl_append]

/-- Rank-local composition from the zero state accumulates exactly the generated state. -/
theorem composeAll_zero (segments : List (State →ᵃ[𝕜] State)) :
    composeAll segments 0 = segments.foldl (fun current next => next current) 0 :=
  composeAll_apply segments 0

end KimiK3.ContextParallel
